import type { TravelPlanResponse } from "./schemas.js";

const MAX_RENDERED_SECTIONS = {
  flights: 5,
  hotels: 5,
  days: 14,
  activitiesPerDay: 4,
  assumptions: 8,
} as const;

export function renderTravelItineraryHtml(
  response: TravelPlanResponse,
): string {
  const plan = response.plan;
  const title = "SABOROU 旅のしおり";

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
:root {
  color-scheme: light;
  --ink: #24323f;
  --muted: #617182;
  --paper: #fffaf0;
  --panel: #ffffff;
  --line: #d8c7a3;
  --accent: #1d7f7a;
  --accent-dark: #135c58;
  --sun: #d9912b;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  color: var(--ink);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.65;
  background:
    linear-gradient(135deg, rgba(29, 127, 122, 0.12), transparent 38%),
    linear-gradient(315deg, rgba(217, 145, 43, 0.14), transparent 42%),
    var(--paper);
}
a { color: var(--accent-dark); font-weight: 700; }
.page {
  width: min(980px, calc(100% - 32px));
  margin: 0 auto;
  padding: 40px 0 56px;
}
.hero {
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.84);
  padding: 32px;
}
.kicker {
  margin: 0 0 8px;
  color: var(--accent-dark);
  font-size: 13px;
  font-weight: 800;
  letter-spacing: 0;
  text-transform: uppercase;
}
h1 {
  margin: 0 0 16px;
  font-size: clamp(32px, 5vw, 56px);
  line-height: 1.08;
  letter-spacing: 0;
}
.summary {
  margin: 0;
  max-width: 760px;
  color: var(--muted);
  font-size: 18px;
}
.grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px;
  margin-top: 24px;
}
.section {
  margin-top: 22px;
  padding: 24px;
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.9);
}
.section h2 {
  margin: 0 0 14px;
  font-size: 22px;
  line-height: 1.25;
  letter-spacing: 0;
}
.card {
  padding: 16px 0;
  border-top: 1px solid rgba(216, 199, 163, 0.7);
}
.card:first-of-type { border-top: 0; padding-top: 0; }
.card h3 {
  margin: 0 0 6px;
  font-size: 18px;
  line-height: 1.35;
  letter-spacing: 0;
}
.meta {
  margin: 0 0 8px;
  color: var(--sun);
  font-weight: 800;
}
.reason {
  margin: 0 0 8px;
  color: var(--muted);
}
.day {
  margin-top: 18px;
  padding-top: 18px;
  border-top: 1px solid rgba(216, 199, 163, 0.7);
}
.day:first-of-type { margin-top: 0; padding-top: 0; border-top: 0; }
.day-title {
  margin: 0 0 10px;
  color: var(--accent-dark);
  font-weight: 900;
}
.timeline {
  display: grid;
  gap: 12px;
}
.timeline-item {
  padding-left: 14px;
  border-left: 4px solid var(--accent);
}
.time {
  margin: 0 0 2px;
  color: var(--sun);
  font-size: 13px;
  font-weight: 900;
}
ul {
  margin: 0;
  padding-left: 20px;
}
li + li { margin-top: 8px; }
.footer {
  margin-top: 18px;
  color: var(--muted);
  font-size: 13px;
}
@media (max-width: 760px) {
  .page { width: min(100% - 20px, 980px); padding: 18px 0 36px; }
  .hero, .section { padding: 20px; }
  .grid { grid-template-columns: 1fr; }
}
</style>
</head>
<body>
  <main class="page">
    <header class="hero">
      <p class="kicker">Travel Itinerary</p>
      <h1>${escapeHtml(title)}</h1>
      <p class="summary">${escapeHtml(plan.summary)}</p>
    </header>
    <div class="grid">
      ${renderFlights(plan.flights)}
      ${renderHotels(plan.hotels)}
    </div>
    ${renderActivities(plan.activitiesByDay)}
    ${renderAssumptions(plan.assumptions)}
    <p class="footer">Generated by SABOROU. Prices and availability may change.</p>
  </main>
</body>
</html>`;
}

export function escapeHtml(value: string): string {
  return redactSensitiveText(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function redactSensitiveText(value: string): string {
  return value
    .replace(/api[-_ ]?token[^\s,;)]*/gi, "[redacted]")
    .replace(/marker[^\s,;)]*/gi, "[redacted]")
    .replace(/trs[^\s,;)]*/gi, "[redacted]")
    .replace(/Authorization[^\n]*/gi, "[redacted]")
    .replace(/Bearer\s+[^\s]+/gi, "[redacted]");
}

function renderFlights(flights: TravelPlanResponse["plan"]["flights"]): string {
  if (flights.length === 0) return "";

  return `<section class="section">
    <h2>フライト候補</h2>
    ${flights
      .slice(0, MAX_RENDERED_SECTIONS.flights)
      .map((flight) => {
        const price = `${flight.price.amount.toLocaleString("ja-JP")}${flight.price.currency}`;
        return `<article class="card">
        <p class="meta">#${flight.rank} ${escapeHtml(price)}</p>
        <h3>${escapeHtml(flight.title)}</h3>
        <p class="reason">${escapeHtml(flight.reason)}</p>
        ${renderLink(flight.bookingUrl, "予約リンク")}
      </article>`;
      })
      .join("")}
  </section>`;
}

function renderHotels(hotels: TravelPlanResponse["plan"]["hotels"]): string {
  if (hotels.length === 0) return "";

  return `<section class="section">
    <h2>ホテル候補</h2>
    ${hotels
      .slice(0, MAX_RENDERED_SECTIONS.hotels)
      .map(
        (hotel) => `<article class="card">
        <p class="meta">${escapeHtml(hotel.area)}</p>
        <h3>${escapeHtml(hotel.name)}</h3>
        <p class="reason">${escapeHtml(hotel.reason)}</p>
        ${renderLink(hotel.bookingUrl, "予約リンク")}
      </article>`,
      )
      .join("")}
  </section>`;
}

function renderActivities(
  days: TravelPlanResponse["plan"]["activitiesByDay"],
): string {
  if (days.length === 0) return "";

  return `<section class="section">
    <h2>日別アクティビティ</h2>
    ${days
      .slice(0, MAX_RENDERED_SECTIONS.days)
      .map(
        (day) => `<article class="day">
      <p class="day-title">${day.day}日目 ${escapeHtml(day.date)}</p>
      <div class="timeline">
        ${day.items
          .slice(0, MAX_RENDERED_SECTIONS.activitiesPerDay)
          .map(
            (item) => `<div class="timeline-item">
          <p class="time">${escapeHtml(item.timeOfDay)}</p>
          <h3>${escapeHtml(item.title)}</h3>
          <p class="reason">${escapeHtml(item.reason)}</p>
          ${renderLink(item.bookingUrl, "詳細リンク")}
        </div>`,
          )
          .join("")}
      </div>
    </article>`,
      )
      .join("")}
  </section>`;
}

function renderAssumptions(assumptions: string[]): string {
  if (assumptions.length === 0) return "";

  return `<section class="section">
    <h2>前提と注意点</h2>
    <ul>
      ${assumptions
        .slice(0, MAX_RENDERED_SECTIONS.assumptions)
        .map((assumption) => `<li>${escapeHtml(assumption)}</li>`)
        .join("")}
    </ul>
  </section>`;
}

function renderLink(url: string | null, label: string): string {
  const safeUrl = sanitizeHttpUrl(url);
  if (!safeUrl) return "";
  return `<a href="${escapeHtml(safeUrl)}" rel="noopener noreferrer">${escapeHtml(label)}</a>`;
}

function sanitizeHttpUrl(url: string | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== "https:" && parsed.protocol !== "http:") {
      return null;
    }
    return parsed.toString();
  } catch {
    return null;
  }
}
